import streamlit as st

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from PIL import Image


st.set_page_config(
    layout="wide"
)
### Headings and logo

col1, _, col3 = st.columns([0.70, 0.1, 0.20])

with col1:
    st.markdown(" ")
    st.title("OUR MISSION")
    # st.subheader("Back testing for Profit and Loss analysis")
    st.write("""Our mission is to assist traders in navigating volatile markets by providing
                them with reliable and actionable signals generated by our advanced machine-learning
                algorithm. We aim to empower traders to make informed and profitable trading decisions
                based on the insights and predictions provided by our algorithm. Through continuous
                optimization and innovation, we strive to deliver the highest quality output, enabling
                traders to achieve their financial goals and succeed in dynamic market environments.""")

with col3:

    image_path = "https://raw.githubusercontent.com/MehmetSever09/assist_trader/master/assets/images/logo_assist_trader_cropped.png"
    border_color = "#FF7F32"
    border_width = 3
    image_width = 250  # in pixels
    image_height = 250  # in pixels

    styled_image = f'<div style="border: {border_width}px solid {border_color}; ' \
                f'width: {image_width}px; height: {image_height}px; ' \
                f'overflow: hidden;">' \
                f'<img src="{image_path}" style="object-fit: cover; ' \
                f'width: 100%; height: 100%;">' \
                f'</div>'

    # Display the styled image
    st.markdown(styled_image, unsafe_allow_html=True)


st.write("\n")
st.write("\n")
st.write("\n")

### Images of the team
st.write("### MEET THE TEAM")

col1, col2, col3 = st.columns(3)
with col1:
    st.write("#### Mehmet")
    image = Image.open("assets/images/mehmet_image.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
with col2:
    st.write("#### Irina")
    image = Image.open("assets/images/irina_image_crop.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
with col3:
    st.write("#### Ferdinand")
    image = Image.open("assets/images/ferdinand_image.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
