import streamlit as st

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from PIL import Image


st.set_page_config(
    layout="wide"
)

st.title("OUR MISSION")

#st.write("""Mission Statement: """)
st.write("""Our mission is to assist traders in navigating volatile markets by providing
            them with reliable and actionable signals generated by our advanced machine-learning
            algorithm. We aim to empower traders to make informed and profitable trading decisions
            based on the insights and predictions provided by our algorithm. Through continuous
            optimization and innovation, we strive to deliver the highest quality output, enabling
            traders to achieve their financial goals and succeed in dynamic market environments.""")
st.write("### MEET THE TEAM")
col1, col2, col3 = st.columns(3)
with col1:
    st.write("#### Mehmet")
    image = Image.open("assets/images/mehmet_image.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
with col2:
    st.write("#### Irina")
    image = Image.open("assets/images/irina_image_crop.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
with col3:
    st.write("#### Ferdinand")
    image = Image.open("assets/images/ferdinand_image.jpg")
    st.image(image, caption="JPG Image", use_column_width=True)
